apiVersion: apps/v1
kind: Deployment
metadata:
  name: anatech-portal-api
  namespace: production
  labels:
    app: anatech-portal-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anatech-portal-api
  template:
    metadata:
      labels:
        app: anatech-portal-api
    spec:
      imagePullSecrets:
      - name: harbor-secret
      containers:
      - name: anatech-portal-api
        image: harbor.anasigorta.com.tr/prod/anatech-api:v1.0.0
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: ASPNETCORE_URLS
          value: "http://0.0.0.0:8080"
        - name: ConnectionStrings__DefaultConnection
          value: "Host=185.87.252.126;Port=6432;Database=anatechdb;Username=anatech_user;Password=AnatechPass2024;"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
