apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-api
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: identity-api
  template:
    metadata:
      labels:
        app: identity-api
    spec:
      imagePullSecrets:
      - name: harbor-secret
      containers:
      - name: identity-api
        image: harbor.anasigorta.com.tr/prod/identity-api:v1.0.0  # ArgoCD bu tag'i otomatik güncelleyecek
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: ASPNETCORE_URLS
          value: "http://0.0.0.0:8080"
        envFrom:
        - configMapRef:
            name: identity-config
        - secretRef:
            name: identity-secrets
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
